plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO Stuff
author: Kev Quirk
title: 512KB Club
tagline: A showcase of lightweight websites.
description: The 512KB Club is an exclusive list of web pages weighing less than 512 kilobytes.
lang: en
locale: en_GB
url: "https://512kb.club"
baseurl: ""
permalink: :title

# Syntax Highlighting
highlighter: rouge

# Netlify redirects
include:
  - _redirects